X, Y = meshgrid(arange(0, 60), arange(0, 50))
Z = exp(-((X-25)**2 + (Y-20)**2)/300) + 0.7*exp(-((X-40)**2 + (Y-35)**2)/200)
SetData2D('z', Z, xrange=(0, 60), yrange=(0, 50))
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'X'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'Y'); Set('direction', 'vertical'); To('..')
Add('contour', name='c1', autoadd=False)
To('c1'); Set('data', 'z'); Set('numLevels', 8); To('..')
To('/')
Export('contour.png', dpi=120)
