from numpy.random import default_rng
r = default_rng(3)
xv = r.normal(0, 1, 100); yv = 0.7*xv + r.normal(0, 0.5, 100)
SetData('x', xv); SetData('y', yv)
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'X'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'Y'); Set('direction', 'vertical'); To('..')
Add('xy', name='pts', autoadd=False)
To('pts'); Set('xData', 'x'); Set('yData', 'y'); Set('marker', 'circle'); Set('PlotLine/hide', True); To('..')
Add('covariance', name='cv1', autoadd=False)
To('cv1'); Set('xData', 'x'); Set('yData', 'y'); To('..')
To('/')
Export('covariance.png', dpi=120)
