Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'f(x)'); Set('direction', 'vertical'); To('..')
Add('function', name='f1', autoadd=False)
To('f1'); Set('function', 'exp(-0.2*x)*sin(x)'); Set('steps', 200); Set('Line/color', 'darkred'); To('..')
To('/')
Export('function.png', dpi=120)
