SetData('x', arange(0, 5)); SetData('y1', [1, 3, 2, 4, 3]); SetData('y2', [2, 1, 4, 2, 5])
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('grid', name='grid1', autoadd=False); To('grid1'); Set('rows', 1); Set('columns', 2)
Add('graph', name='ga', autoadd=False); To('ga')
Add('axis', name='x', autoadd=False); To('x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('direction', 'vertical'); To('..')
Add('xy', name='xy1', autoadd=False); To('xy1'); Set('xData', 'x'); Set('yData', 'y1'); To('..'); To('..')
Add('graph', name='gb', autoadd=False); To('gb')
Add('axis', name='x', autoadd=False); To('x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('direction', 'vertical'); To('..')
Add('xy', name='xy2', autoadd=False); To('xy2'); Set('xData', 'x'); Set('yData', 'y2'); Set('PlotLine/color', 'darkred'); To('..')
To('..'); To('..'); To('/')
Export('grid.png', dpi=120)
