SetData('x', arange(0, 5)); SetData('y', [1, 2, 4, 8, 16])
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'y'); Set('direction', 'vertical'); To('..')
Add('xy', name='xy1', autoadd=False); To('xy1'); Set('xData', 'x'); Set('yData', 'y'); Set('marker', 'circle'); Set('PlotLine/hide', True); To('..')
Add('label', name='lb1', autoadd=False); To('lb1'); Set('label', 'Growth region'); Set('xPos', 3.2); Set('yPos', 14.0); To('..')
Add('line', name='ln1', autoadd=False); To('ln1'); Set('mode', 'point-to-point'); Set('xPos', 3.0); Set('yPos', 12.0); Set('xPos2', 3.8); Set('yPos2', 16.0); Set('arrowright', 'arrow'); To('..')
To('/')
Export('label_shape.png', dpi=120)
