t = arange(0, 6.3, 0.1)
SetData('theta', t); SetData('r', 1 + 0.6*sin(3*t))
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('polar', name='pol1', autoadd=False); To('pol1'); Set('units', 'radians')
Add('nonorthpoint', name='np1', autoadd=False)
To('np1'); Set('data1', 'r'); Set('data2', 'theta'); Set('marker', 'circle'); Set('PlotLine/hide', False); To('..')
To('/')
Export('polar.png', dpi=120)
