SetData('a', [0.1, 0.3, 0.5, 0.7, 0.2, 0.4, 0.6, 0.8]); SetData('b', [0.3, 0.4, 0.2, 0.1, 0.5, 0.3, 0.2, 0.1])
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('ternary', name='ter1', autoadd=False); To('ter1')
Set('labelbottom', 'A'); Set('labelleft', 'B'); Set('labelright', 'C')
Add('nonorthpoint', name='np1', autoadd=False)
To('np1'); Set('data1', 'a'); Set('data2', 'b'); Set('marker', 'circle'); Set('PlotLine/hide', True); To('..')
To('/')
Export('ternary.png', dpi=120)
