SetData('x', arange(0, 10)); SetData('y', [1, 2, 1.5, 3, 45, 50, 52, 2, 2.5, 1.8])
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis-broken', name='x', autoadd=False); To('x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('direction', 'vertical'); To('..')
Add('xy', name='xy1', autoadd=False); To('xy1'); Set('xData', 'x'); Set('yData', 'y'); To('..')
To('/')
Export('axisbroken.png', dpi=120)
