from numpy.random import default_rng
r = default_rng(9)
x = arange(0, 10, 0.5); y = 2.5 + 1.3*x + r.normal(0, 0.4, x.size)
SetData('x', x, symerr=0.3*ones(x.size)); SetData('y', y)
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'x'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'y'); Set('direction', 'vertical'); To('..')
Add('xy', name='pts', autoadd=False); To('pts'); Set('xData', 'x'); Set('yData', 'y'); Set('marker', 'circle'); Set('PlotLine/hide', True); To('..')
Add('fit', name='fit1', autoadd=False); To('fit1'); Set('xData', 'x'); Set('yData', 'y'); Set('function', 'a + b*x'); Set('values', {'a': 0.0, 'b': 1.0}); To('..')
Action('fit', 'fit1')
Add('key', name='key1', autoadd=False); To('key1'); Set('Border/hide', True); Set('horzPosn', 'right'); Set('vertPosn', 'top'); To('..')
To('/')
Export('fit.png', dpi=120)
