X, Y = meshgrid(arange(0, 20), arange(0, 15))
SetData2D('dx', -Y/3.0, xrange=(0,20), yrange=(0,15))
SetData2D('dy', X/3.0, xrange=(0,20), yrange=(0,15))
Set('width', '8cm'); Set('height', '6cm')
Add('page', name='page1', autoadd=False); To('page1')
Add('graph', name='g1', autoadd=False); To('g1')
Add('axis', name='x', autoadd=False); To('x'); Set('label', 'X'); To('..')
Add('axis', name='y', autoadd=False); To('y'); Set('label', 'Y'); Set('direction', 'vertical'); To('..')
Add('vectorfield', name='v1', autoadd=False)
To('v1'); Set('data1', 'dx'); Set('data2', 'dy'); Set('mode', 'cartesian'); To('..')
To('/')
Export('vectorfield.png', dpi=120)
